### ISSUE TITLE
parse error meta-ettus

### ISSUE THREAD

**Issue by viktorivan** [balister/oe-gnuradio-manifest#5]
Hi, I get the following error...

ERROR: Unable to parse /home/ivan/oe-repo/oe-core/../meta-ettus/conf/layer.conf: file /home/ivan/oe-repo/oe-core/../meta-ettus/conf/layer.conf not found

Its occurs with bitbake

bitbake gnuradio-dev-image

Do you have any suggestions?

**Comment by balister** [comment]
what repo init command did you use? You may need to adjust the conf/bblayers.conf file.

**Comment by balister** [comment]
Yep, I see the issue. The bblayers template file was  changed accidentally to a new meta-ettus layout that isn't present in meta-ettus/fido. UNles you are building for an ettus board, remove the line from bblayers.conf, or change it to meta-etuus/e300-bsp. Both should resolve the issue. I'll update the template files and close this report. Thanks, Philip

**Comment by viktorivan** [comment]
I am working with a Zedboard, I remove the meta-ettus line in the bblayers.conf?

**Comment by balister** [comment]
Yep

**Comment by balister** [comment]
There is another issue with boot.bin not getting built right, so it will not boot. But you should be able to use a good one.

**Comment by viktorivan** [comment]
ok, thanks...

**Comment by balister** [comment]
The bblayers issue should be fixed with 130249739582216f64c60534feec5f71848bf5dd
